#! /bin/bash

ln -sfv ~/etc/sbin/make-etc-links ~/bin

echo

for i in           \
    Xmodmap        \
    aliases        \
    bash_logout    \
    bash_profile   \
    bashrc         \
    perltidyrc     \
    screenrc       \
    vimrc          \
; do
    ln -sfv ~/etc/$i ~/.$i
done

if [ $OS_TYPE != "darwin" ]; then
    ln -sfv ~/etc/xinitrc ~/.xinitrc
fi

echo 

rm -f ~/.vim
ln -sfv ~/etc/vim                ~/.vim

echo

rm -f ~/.dzil
ln -sfv ~/etc/dzil ~/.dzil

echo
