#! /bin/bash

ln -sfv ~/etc/sbin/make-etc-links ~/bin

echo

for i in           \
    Xmodmap        \
    aliases        \
    bash_logout    \
    bash_profile   \
    bashrc         \
    screenrc       \
; do
    ln -sfv ~/etc/$i ~/.$i
done

if [ $OS_TYPE != "darwin" ]; then
    ln -sfv ~/etc/xinitrc ~/.xinitrc
fi

if [ -e /opt/awesome ]; then
    mkdir -p ~/.config/awesome
    ln -sfv ~/etc/awesome/rc.lua ~/.config/awesome/
fi

echo 

rm -f ~/.vim
ln -sfv ~/etc/vim/vimrc          ~/.vimrc
ln -sfv ~/etc/vim                ~/.vim

echo

