#! /bin/bash

# $Id$
# $URL$

ln -sfv ~/etc/sbin/make-etc-links ~/bin

echo

for i in           \
    Xdefaults      \
    aliases        \
    awesomerc      \
    bash_logout    \
    bash_profile   \
    bashrc         \
    conkyrc        \
    cvsrc          \
    screenrc       \
; do
    ln -sfv ~/etc/$i ~/.$i
done

if [ $GENEHACK_LOCATION != "LAPTOP" ]; then
    ln -sfv ~/etc/xinitrc ~/.xinitrc
fi

echo 

ln -sfv ~/etc/subversion/config  ~/.subversion/config
ln -sfv ~/etc/subversion/servers ~/.subversion/servers
ln -sfv ~/etc/vim/vimrc          ~/.vimrc

echo

rm -f ~/.module-starter 
if [ $GENEHACK_LOCATION = "WORK" ]; then
    ln -sfv ~/etc/module-starter-work ~/.module-starter
else
    ln -sfv ~/etc/module-starter ~/.module-starter
fi

rm -f ~/.vim             && ln -sfv ~/etc/vim            ~/.vim
